# Generated by Django 4.0.5 on 2022-06-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='detials',
            new_name='details',
        ),
    ]
